[build]
  publish = "public"
  functions = "netlify/functions"
  command = ""

[[plugins]]
package = "@netlify/plugin-emails"

[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 301
  force = true

[[redirects]]
  from = "/team"
  to = "/team.html"
  status = 301
  force = true

[[redirects]]
  from = "/services"
  to = "/services.html"
  status = 301
  force = true

[[redirects]]
  from = "/programs"
  to = "/programs.html"
  status = 301
  force = true

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 301
  force = true

[[redirects]]
  from = "/privacy-policy"
  to = "/privacy-policy.html"
  status = 301
  force = true

[[redirects]]
  from = "/terms-conditions"
  to = "/terms-conditions.html"
  status = 301
  force = true

[[redirects]]
  from = "/no-surprises"
  to = "/no-surprises.html"
  status = 301
  force = true