[build]
  publish = "public" # Root directory
  functions = "netlify/functions"
  command = ""

[build.environment]
  NODE_VERSION = "22"

[[plugins]]
package = "@netlify/plugin-emails"

[[redirects]]
  from = "/about-us"
  to = "/about.html"
  status = 301

[[redirects]]
  from = "/team"
  to = "/team.html"
  status = 301

[[redirects]]
  from = "/our-team"
  to = "/team.html"
  status = 301